### SERVER
server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful

### SPRING
spring:
  application:
    name: challenge
  output:
    ansi:
      enabled: ALWAYS

### LOGGING
logging:
  level:
    root: INFO
    com:
      example: TRACE

### SWAGGER
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
    operationsSorter: method